### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by Rainson12** [Sethuramalingam-art/EventApp#1]
You copied the code of `Sanidhya Kumar Verma` who states in his license file that you must include the MIT license:  `The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`

original repo: https://github.com/sanidhyy/evently

**Comment by Sethuramalingam-art** [comment]
> You copied the code of `Sanidhya Kumar Verma` who states in his license file that you must include the MIT license:  `The above copyright notice and this permission notice shall be included in all
> 
> copies or substantial portions of the Software.`
> 
> 
> 
> original repo: https://github.com/sanidhyy/evently

Hey @Rainson12 I chose this project from YouTube and I followed the steps how they are coded and I am not copied the code. I have coded line by line for Nextjs self learning. Yes original code is from Sandhiya Kumar's but I have learnt the things from him what's wrong on this?
